<script setup lang="ts">
import { useI18n } from '../composables/useI18n';
import type { OceanPointEstimate } from '../api/types';

defineProps<{
  lat: number;
  lng: number;
  loading: boolean;
  error: string | null;
  point: OceanPointEstimate | null;
}>();
defineEmits<{ close: [] }>();
const { t } = useI18n();
</script>

<template>
  <div class="ocean-point-card">
    <button class="close-btn" @click="$emit('close')">×</button>
    <h4>{{ t('oceanPoint.title') }}</h4>
    <div class="coords">{{ lat.toFixed(3) }}, {{ lng.toFixed(3) }}</div>

    <p v-if="loading" class="status">{{ t('oceanPoint.loading') }}</p>
    <p v-else-if="error" class="status error">{{ error }}</p>
    <template v-else-if="point">
      <div class="row">
        <span>{{ t('oceanPoint.sst') }}</span><b>{{ point.sst_c }}°C</b>
      </div>
      <div class="row">
        <span>{{ t('oceanPoint.salinity') }}</span
        ><b>{{ point.salinity_psu }} psu</b>
      </div>
      <div class="row">
        <span>{{ t('oceanPoint.chlorophyll') }}</span
        ><b>{{ point.chlorophyll_mg_m3 }} mg/m³</b>
      </div>
      <div class="row">
        <span>{{ t('oceanPoint.nearestStation') }}</span
        ><b>{{ point.nearest_station }} · {{ point.nearest_station_km }} km</b>
      </div>
      <!-- methodology is generated by the backend per-click (station names/
      distances vary), not a fixed UI string — outside the static i18n
      system by design, same treatment as chat answers. -->
      <p class="note">{{ point.methodology }}</p>
    </template>
  </div>
</template>

<style scoped>
.ocean-point-card {
  position: fixed;
  top: 390px;
  right: 20px;
  z-index: 20;
  background: var(--surface);
  border: 1px solid var(--border);
  border-radius: 10px;
  padding: 14px 16px;
  box-shadow: var(--shadow);
  width: 200px;
}
.close-btn {
  position: absolute;
  top: 8px;
  right: 10px;
  background: none;
  border: none;
  color: var(--muted);
  font-size: 12px;
  cursor: pointer;
  font-family: var(--font-mono);
}
h4 {
  font-family: var(--font-mono);
  font-size: 9.5px;
  text-transform: uppercase;
  letter-spacing: 0.08em;
  color: var(--muted);
  margin-bottom: 6px;
  padding-right: 16px;
}
.coords {
  font-family: var(--font-mono);
  font-size: 11px;
  color: var(--teal);
  margin-bottom: 10px;
}
.status {
  font-size: 12px;
  color: var(--muted);
}
.status.error {
  color: var(--coral);
}
.row {
  display: flex;
  justify-content: space-between;
  gap: 8px;
  font-size: 12px;
  padding: 4px 0;
}
.row span {
  color: var(--muted);
}
.row b {
  color: var(--text);
  font-weight: 600;
  text-align: right;
}
.note {
  font-size: 9.5px;
  color: var(--muted);
  line-height: 1.4;
  margin-top: 8px;
  border-top: 1px dashed var(--border);
  padding-top: 8px;
}
</style>
